Confirm if 8.x is supported
PrestaShop/ps_newproducts pull request #27
Opened 2024-05-14 19:12 UTC by fulldecent

Please confirm if 8.x is supported so I can include this on https://github.com/fulldecent/awesome-prestashop-modules/edit/main/README.md

2024-05-14 20:17 UTC, Hlavtox requested changes
I like the original better. 1.7.7.0 and later means 8.x is supported. ;) Native modules are always supported by the latest version.

If we change it, we would need to add 9.0, 10.0 everywhere, too much work 😁

2024-05-14 21:22 UTC, fulldecent commented
9.0 is currently in development, is that supported as well?

Please note that issues are closed on this Goodhope repo. That means I cannot see if anybody has ever actually tried to use this module  8. X and had any success. 

please also note that many many modules on GitHub for Presto shop are outdated and completely a waste of time to open. Your reassurance here is helpful to me to know that this runs on 8.X. However, it would be very helpful for the community to see that this is actually supported, and that improvements to this module are still being accepted.

2024-05-15 08:48 UTC, Hlavtox commented
@fulldecent I will answer in points, hope I will clarify everything. Some things may be written, some may not. :-)

- All native modules on https://github.com/PrestaShop/ repository SHOULD and in 99 % of cases are compatible even with the develop version that is coming (9.0 right now). Some MAY be temporarily broken, but they will be resolved before the core released.
- Issues on module repositories should be closed everywhere, it was decided that all issues will be in the main repo. Sometimes the issues are interconnected with each other, so one place that has everything. There may be some exceptions like Hummingbird theme, that has issues enabled, but that was mostly so we don't bloat the main repo with "development" issues.
- Native modules that are outdated and no longer receive any updates are marked as archived/read-only. All other modules are actively supported, get maintained and are accepting contributions. 👍
- 3rd party module authors must specify the compatibility themselves. Sad truth is that 99 % of themes/modules everywhere SAY that they are compatible with latest version, but they are in fact not.
  - This is an endless point of arguments with customers, when there is a job to resolve some issue.
  - You find out that the cause is in a module, you tell the customer that he needs to contact the author of the module.
  - The customer looks on Addons or any other store or contact the author, and he will tell him that it works, while you can SEE that it doesnt.

2024-05-20 04:38 UTC, fulldecent commented
Okay, I see we are both concerned about these things. Maybe there's some opportunities here.

1. We can use README.md to link to the correct place to send issues (for PrestaShop official repos). This will allow people to see that feedback is allowed, and this is not a ghosted project.

2. We can show exactly which versions are supported by testing for each of them in GitHub Actions, and including that status badge. One of the supported PrestaShop versions should be "latest" or "main" (git), which tracks the next version. 

We can make this the best practice and the community can demand other modules to adopt this. So then it will be plain and clear which versions are supported.

---

Yes, it really sucks wasting time with third party modules that don't just work.

2024-06-07 13:25 UTC, matks requested changes
Hello as explained by @Hlavtox  8.x is supported however I am not convinced this change is a good idea

Else, we'll have to come again on this README when we release PrestaShop v9, and PrestaShop v10, and ... 😄 

I have read your statement and I understand this change could help some users to be "reassured" this software is maintained or not. But this change would come at a cost, the cost I mentioned above.

> We can use README.md to link to the correct place to send issues (for PrestaShop official repos). This will allow people to see that feedback is allowed, and this is not a ghosted project.

I'm sorry but I think you are overthinking things 😄 . Maybe your mind reasons this way, but I dont think this is the majority. I don't think people go "oh, this repository does not talk about 8.x branch then it must be ghosted"

I guess you won't agree with me 😉 but I kindly reject this change

2025-03-12 12:01 UTC, closed without merging